DROP TABLE IF EXISTS Genre cascade;
DROP TABLE IF EXISTS Mpa cascade;
DROP TABLE IF EXISTS filmGenres cascade;
DROP TABLE IF EXISTS Film cascade;
DROP TABLE IF EXISTS Likes cascade;
DROP TABLE IF EXISTS Users cascade;
DROP TABLE IF EXISTS UserFriends cascade;
DROP TABLE IF EXISTS FriendshipStatus cascade;

CREATE TABLE IF NOT EXISTS Mpa
(
    mpaId int          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Film
(
    filmId      int          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    releaseDate timestamp    NOT NULL,
    duration    int          NOT NULL,
    mpa         int          NOT NULL,
    FOREIGN KEY (mpa) REFERENCES mpa (mpaId)
);

CREATE TABLE IF NOT EXISTS Users
(
    userId   int          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255) NOT NULL UNIQUE,
    login    varchar(255) NOT NULL,
    name     varchar(255) NOT NULL,
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS Likes
(
    filmId int NOT NULL,
    userId int NOT NULL,
    FOREIGN KEY (filmId) REFERENCES film (filmId),
    FOREIGN KEY (userId) REFERENCES users (userId)
);

CREATE TABLE IF NOT EXISTS UserFriends
(
    userId   int NOT NULL,
    friendId int NOT NULL,
    status   int NOT NULL,
    FOREIGN KEY (userId) REFERENCES users (userId),
    FOREIGN KEY (friendId) REFERENCES users (userId)
);

CREATE TABLE IF NOT EXISTS FriendshipStatus
(
    id   int          NOT NULL,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre
(
    genreId   int     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genreName varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS filmGenres
(
    filmId  int NOT NULL,
    genreId int NOT NULL,
    FOREIGN KEY (filmId) REFERENCES film (filmId),
    FOREIGN KEY (genreId) REFERENCES genre (genreId)
);
